TOOLS_LIST = [
    ("ENABLE_NAMINTER", "Naminter (username search)"),
    ("ENABLE_SHERLOCK", "Sherlock (username search)"),
    ("ENABLE_SOCIAL_ANALYZER", "Social Analyzer (fast check)"),
    ("ENABLE_LINKOOK", "Linkook (deep URL discovery)"),
    ("ENABLE_SOCIOPATH", "Sociopath (URL spider)"),
    ("ENABLE_SHARETRACE", "ShareTrace (tracking link resolver)"),
    ("ENABLE_SOCID", "Socid Extractor (profile data)"),
    ("ENABLE_GITFIVE", "GitFive (GitHub emails/history)"),
    ("ENABLE_TOUTATIS", "Toutatis (Instagram, needs session)"),
    ("ENABLE_THEHARVESTER", "theHarvester (domain emails)"),
    ("ENABLE_NAME_ANALYSIS", "NameTrace & Fuzzy matching"),
    ("ENABLE_FACE_MATCH", "Face matching (disabled)"),
    ("ENABLE_EMAIL_GUESS", "Email permuter/guesser"),
    ("ENABLE_HOLEHE", "Holehe (used on sites)"),
    ("ENABLE_H8MAIL", "h8mail (breach check)"),
    ("ENABLE_GOSEARCH", "Gosearch"),
    ("ENABLE_GHUNT", "GHunt (Google account info)"),
    ("ENABLE_PHONEINFOGA", "PhoneInfoga"),
    ("ENABLE_AI_REPORT", "AI report generation (Groq)"),
    ("ENABLE_MAIGRET", "Maigret (full username search)"),
    ("ENABLE_REVERSE_IMG", "Reverse image search (SauceNAO)"),
    ("ENABLE_SOCIALSCAN", "socialscan for URL filtering"),
    ("ENABLE_EXIF", "EXIF metadata extraction"),
    ("ENABLE_WHOIS", "WHOIS domain lookups"),
    ("ENABLE_WAYBACK", "Wayback Machine check"),
    ("ENABLE_HIBP", "HaveIBeenPwned (HIBP)"),
    ("ENABLE_EMAILREP", "EmailRep.io"),
    ("ENABLE_SCYLLA", "Scylla (leak DB)"),
    ("ENABLE_LOCATION", "Location inference from bio"),
    ("ENABLE_LANGDETECT", "Language detection"),
    ("ENABLE_PARALLEL_EMAIL", "Parallel email checks"),
    ("ENABLE_CACHING", "Cache intel between runs"),
    ("ENABLE_BLACKBIRD", "Blackbird (email & username search, 600+ sites)"),
]
